package catalogue

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"
)

// generatedByActor is this package's own OKF 0.2 `generated.by` actor
// identifier -- the "<producer>/<version>" convention the spec names for
// an automated agent, not a human or a process id.
const generatedByActor = "agent-estate-sourcecatalogue/v1"

// okfStatus maps a RegisterEntry's own EntryStatus onto OKF 0.2's
// three-value `status` enum (draft/stable/deprecated). StatusNeedsReview
// maps to "draft" -- "not yet reviewed", which is exactly what a drift
// flip means -- never "deprecated", which OKF reserves for a retired
// record kept only for links and history; a needs-review source is
// still the live record, just one this package will not vouch for as
// current until a human looks at it again.
func okfStatus(s EntryStatus) string {
	if s == StatusNeedsReview {
		return "draft"
	}
	return "stable"
}

// GenerateSourceView renders one RegisterEntry as an OKF 0.2 Markdown
// record whose frontmatter carries agent-estate-lanes/run/contract.md
// §1's own field names verbatim (id, locator, kind, provenance,
// attribution, authority, access, revision, observed-at, freshness,
// review-state, derivative-links) alongside OKF's own required `type`
// and its `generated`/`status` keys. The register is the only update
// path for this file's content -- the header says so explicitly, so a
// reader who opens it in the staging tree never mistakes it for
// something safe to hand-edit.
func GenerateSourceView(e RegisterEntry, now time.Time) string {
	var b strings.Builder
	fmt.Fprintf(&b, "---\n")
	fmt.Fprintf(&b, "type: Source Record\n")
	fmt.Fprintf(&b, "sources:\n")
	fmt.Fprintf(&b, "  - resource: %s\n", yamlQuote(e.Locator))
	fmt.Fprintf(&b, "    title: %s\n", yamlQuote(fmt.Sprintf("%s (%s)", e.Kind, e.ID)))
	fmt.Fprintf(&b, "generated:\n")
	fmt.Fprintf(&b, "  by: %s\n", generatedByActor)
	fmt.Fprintf(&b, "  at: %s\n", now.UTC().Format(time.RFC3339))
	fmt.Fprintf(&b, "status: %s\n", okfStatus(e.Status))
	fmt.Fprintf(&b, "id: %s\n", e.ID)
	fmt.Fprintf(&b, "locator: %s\n", yamlQuote(e.Locator))
	fmt.Fprintf(&b, "kind: %s\n", yamlQuote(e.Kind))
	fmt.Fprintf(&b, "provenance: %s\n", yamlQuote(e.Provenance))
	fmt.Fprintf(&b, "attribution: %s\n", yamlQuote(e.Attribution))
	fmt.Fprintf(&b, "authority: %s\n", yamlQuote(e.Authority))
	fmt.Fprintf(&b, "access: %s\n", yamlQuote(e.Access))
	fmt.Fprintf(&b, "revision: %s\n", yamlQuote(e.ObservedRevision))
	fmt.Fprintf(&b, "observed-at: %s\n", e.LastRefreshedAt.UTC().Format(time.RFC3339))
	fmt.Fprintf(&b, "freshness: %s\n", yamlQuote(e.Freshness))
	fmt.Fprintf(&b, "review-state: %s\n", yamlQuote(e.ReviewState))
	if len(e.DerivativeLinks) > 0 {
		fmt.Fprintf(&b, "derivative-links:\n")
		for _, l := range e.DerivativeLinks {
			fmt.Fprintf(&b, "  - %s\n", yamlQuote(l))
		}
	}
	fmt.Fprintf(&b, "catalogue_extraction_kind: %s\n", e.ExtractionKind)
	fmt.Fprintf(&b, "catalogue_status: %s\n", e.Status)
	fmt.Fprintf(&b, "registered_at: %s\n", e.RegisteredAt.UTC().Format(time.RFC3339))
	fmt.Fprintf(&b, "---\n\n")

	fmt.Fprintf(&b, "<!-- GENERATED by cmd/sourcecatalogue -- do not hand-edit. The private\n")
	fmt.Fprintf(&b, "     register (%s) is the only update path; re-run `sourcecatalogue\n", registerFileName)
	fmt.Fprintf(&b, "     refresh` or `register` to change this file. -->\n\n")

	fmt.Fprintf(&b, "# %s\n\n", e.ID)
	fmt.Fprintf(&b, "**Kind:** %s  \n", e.Kind)
	fmt.Fprintf(&b, "**Locator:** %s  \n", e.Locator)
	fmt.Fprintf(&b, "**Review state:** %s  \n", e.ReviewState)
	fmt.Fprintf(&b, "**Drift status:** %s  \n\n", e.Status)

	fmt.Fprintf(&b, "## Why indexed\n\n%s\n\n", nonEmpty(e.WhyIndexed))
	fmt.Fprintf(&b, "## Provenance (who produced this record)\n\n%s\n\n", nonEmpty(e.Provenance))
	fmt.Fprintf(&b, "## Attribution (who authored the original)\n\n%s\n\n", nonEmpty(e.Attribution))
	fmt.Fprintf(&b, "## Authority\n\n%s\n\n", nonEmpty(e.Authority))
	fmt.Fprintf(&b, "## Scope\n\n%s\n\n", nonEmpty(e.Scope))
	fmt.Fprintf(&b, "## Access\n\n%s%s\n\n", nonEmpty(e.Access), accessDetailSuffix(e.AccessDetail))
	fmt.Fprintf(&b, "## Owner\n\n%s\n\n", nonEmpty(e.Owner))
	fmt.Fprintf(&b, "## Freshness\n\n%s\n\n", nonEmpty(e.Freshness))
	fmt.Fprintf(&b, "## Extraction\n\n%s\n\n", nonEmpty(e.ExtractionStatus))

	if len(e.DerivativeLinks) > 0 {
		fmt.Fprintf(&b, "## Reviewed derivatives\n\n")
		for _, l := range e.DerivativeLinks {
			fmt.Fprintf(&b, "- %s\n", l)
		}
		fmt.Fprintf(&b, "\n")
	}

	return b.String()
}

func accessDetailSuffix(detail string) string {
	if detail == "" {
		return ""
	}
	return " -- " + detail
}

func nonEmpty(s string) string {
	if s == "" {
		return "(not stated)"
	}
	return s
}

// yamlQuote wraps s in double quotes and escapes the two characters that
// would otherwise break a double-quoted YAML scalar -- adequate for the
// values this package puts through it (locators, titles, hashes), never
// meant as a general YAML encoder.
func yamlQuote(s string) string {
	s = strings.ReplaceAll(s, `\`, `\\`)
	s = strings.ReplaceAll(s, `"`, `\"`)
	return `"` + s + `"`
}

// viewFileName is the Markdown filename one entry's view is written
// under -- its own id, which is filesystem-safe by construction
// (identityFor only ever produces "src-<16 hex chars>").
func viewFileName(e RegisterEntry) string {
	return e.ID + ".md"
}

// WriteViewsStaging renders every entry in entries and writes it under
// stagingDir/"01 - Sources"/<id>.md, overwriting whatever was there.
// Because every call regenerates every current entry's file from
// scratch, a rerun after an interruption (the process killed mid-loop,
// a partial previous write) always leaves a consistent, complete set of
// views for the entries the register actually has -- deliverable 4's
// "interrupted view generation repairs on rerun." It never writes
// outside stagingDir and never touches the live vault.
func WriteViewsStaging(entries []RegisterEntry, stagingDir string, now time.Time) (int, error) {
	dir := filepath.Join(stagingDir, "01 - Sources")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return 0, err
	}
	sorted := make([]RegisterEntry, len(entries))
	copy(sorted, entries)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].ID < sorted[j].ID })

	for _, e := range sorted {
		content := GenerateSourceView(e, now)
		path := filepath.Join(dir, viewFileName(e))
		tmp := path + ".tmp"
		if err := os.WriteFile(tmp, []byte(content), 0o644); err != nil {
			return 0, err
		}
		if err := os.Rename(tmp, path); err != nil {
			return 0, err
		}
	}
	return len(sorted), nil
}
