package catalogue

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"
)

func fixtureEntry() RegisterEntry {
	return RegisterEntry{
		ID:               "src-abcdef0123456789",
		Kind:             "kind/doc",
		ExtractionKind:   ExtractionRepoDocs,
		Locator:          "/fixture/doc.md",
		Provenance:       "fixture provenance",
		Attribution:      "fixture attribution",
		Authority:        "fixture authority",
		Scope:            "fixture scope",
		Access:           "private",
		Owner:            "fixture owner",
		Freshness:        "fixture freshness",
		ReviewState:      DefaultReviewState,
		WhyIndexed:       "fixture reason",
		ObservedRevision: "deadbeef",
		Status:           StatusActive,
		ExtractionStatus: "extracted: fixture",
		RegisteredAt:     time.Date(2026, 9, 6, 0, 0, 0, 0, time.UTC),
		LastRefreshedAt:  time.Date(2026, 9, 6, 1, 0, 0, 0, time.UTC),
	}
}

func TestGenerateSourceView_HasOKFFrontmatterAndGeneratedMarker(t *testing.T) {
	out := GenerateSourceView(fixtureEntry(), time.Date(2026, 9, 6, 2, 0, 0, 0, time.UTC))
	if !strings.HasPrefix(out, "---\ntype: Source\n") {
		t.Fatalf("view does not open with OKF 0.2 frontmatter: %q", out[:min(60, len(out))])
	}
	if !strings.Contains(out, "generated:\n  by: agent-estate-sourcecatalogue/v1\n") {
		t.Fatalf("missing OKF generated.by marker:\n%s", out)
	}
	if !strings.Contains(out, "status: stable") {
		t.Fatalf("StatusActive entry should map to OKF status stable:\n%s", out)
	}
	if !strings.Contains(out, "GENERATED by cmd/sourcecatalogue -- do not hand-edit") {
		t.Fatalf("missing generated-header marker:\n%s", out)
	}
}

func TestGenerateSourceView_NeedsReviewMapsToDraft(t *testing.T) {
	e := fixtureEntry()
	e.Status = StatusNeedsReview
	out := GenerateSourceView(e, time.Now())
	if !strings.Contains(out, "status: draft") {
		t.Fatalf("StatusNeedsReview entry should map to OKF status draft:\n%s", out)
	}
}

// TestGenerateSourceView_TagsNeverCarryKindAsANamespacedTag is this fix's
// own regression guard (P1.5, inmaps-spec section 3): kind already has
// its own dedicated frontmatter field on a source view -- putting it into
// tags a second time as "kind/doc" is both namespaced (violating the
// flat-lowercase tag rule) and a kind value in tags at all (which section
// 3 forbids outright). The fixture's own Kind is "kind/doc", so if this
// regresses, this test fails on the fixture default -- no separate broken
// fixture is needed to catch it.
func TestGenerateSourceView_TagsNeverCarryKindAsANamespacedTag(t *testing.T) {
	out := GenerateSourceView(fixtureEntry(), time.Now())
	line := ""
	for _, l := range strings.Split(out, "\n") {
		if strings.HasPrefix(l, "tags: ") {
			line = l
			break
		}
	}
	if line == "" {
		t.Fatalf("no tags: line found:\n%s", out)
	}
	if strings.Contains(line, "/") {
		t.Fatalf("tags line carries a namespaced (slash-containing) value: %q", line)
	}
	if !strings.Contains(out, "kind: \"kind/doc\"") {
		t.Fatalf("kind's own dedicated frontmatter field is missing or changed:\n%s", out)
	}
}

func TestWriteViewsStaging_WritesOneFilePerEntry(t *testing.T) {
	dir := t.TempDir()
	entries := []RegisterEntry{fixtureEntry()}
	n, err := WriteViewsStaging(entries, dir, time.Now())
	if err != nil {
		t.Fatalf("WriteViewsStaging: %v", err)
	}
	if n != 1 {
		t.Fatalf("n = %d, want 1", n)
	}
	path := filepath.Join(dir, "05 - Sources", "SRC-2026-09-06-001.md")
	if _, err := os.Stat(path); err != nil {
		t.Fatalf("expected view file at %s: %v", path, err)
	}
}

func TestWriteViewsStaging_RerunIsConsistentAfterPartialState(t *testing.T) {
	dir := t.TempDir()
	stagingSources := filepath.Join(dir, "05 - Sources")
	os.MkdirAll(stagingSources, 0o755)
	// Simulate a leftover partial write from an interrupted prior run.
	os.WriteFile(filepath.Join(stagingSources, "SRC-2026-09-06-001.md.tmp"), []byte("garbage"), 0o644)

	entries := []RegisterEntry{fixtureEntry()}
	if _, err := WriteViewsStaging(entries, dir, time.Now()); err != nil {
		t.Fatalf("WriteViewsStaging: %v", err)
	}
	data, err := os.ReadFile(filepath.Join(stagingSources, "SRC-2026-09-06-001.md"))
	if err != nil {
		t.Fatalf("reading regenerated view: %v", err)
	}
	if strings.Contains(string(data), "garbage") {
		t.Fatalf("regenerated view carried over stale partial content")
	}
}

func min(a, b int) int {
	if a < b {
		return a
	}
	return b
}
