package catalogue

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"
)

func fixtureEntry() RegisterEntry {
	return RegisterEntry{
		ID:               "src-abcdef0123456789",
		Kind:             "kind/doc",
		ExtractionKind:   ExtractionRepoDocs,
		Locator:          "/fixture/doc.md",
		Provenance:       "fixture provenance",
		Attribution:      "fixture attribution",
		Authority:        "fixture authority",
		Scope:            "fixture scope",
		Access:           "private",
		Owner:            "fixture owner",
		Freshness:        "fixture freshness",
		ReviewState:      DefaultReviewState,
		WhyIndexed:       "fixture reason",
		ObservedRevision: "deadbeef",
		Status:           StatusActive,
		ExtractionStatus: "extracted: fixture",
		RegisteredAt:     time.Date(2026, 9, 6, 0, 0, 0, 0, time.UTC),
		LastRefreshedAt:  time.Date(2026, 9, 6, 1, 0, 0, 0, time.UTC),
	}
}

func TestGenerateSourceView_HasOKFFrontmatterAndGeneratedMarker(t *testing.T) {
	out := GenerateSourceView(fixtureEntry(), time.Date(2026, 9, 6, 2, 0, 0, 0, time.UTC))
	if !strings.HasPrefix(out, "---\ntype: Source\n") {
		t.Fatalf("view does not open with OKF 0.2 frontmatter: %q", out[:min(60, len(out))])
	}
	if !strings.Contains(out, "generated:\n  by: agent-estate-sourcecatalogue/v1\n") {
		t.Fatalf("missing OKF generated.by marker:\n%s", out)
	}
	if !strings.Contains(out, "status: stable") {
		t.Fatalf("StatusActive entry should map to OKF status stable:\n%s", out)
	}
	if !strings.Contains(out, "GENERATED by cmd/sourcecatalogue -- do not hand-edit") {
		t.Fatalf("missing generated-header marker:\n%s", out)
	}
}

func TestGenerateSourceView_NeedsReviewMapsToDraft(t *testing.T) {
	e := fixtureEntry()
	e.Status = StatusNeedsReview
	out := GenerateSourceView(e, time.Now())
	if !strings.Contains(out, "status: draft") {
		t.Fatalf("StatusNeedsReview entry should map to OKF status draft:\n%s", out)
	}
}

// TestGenerateSourceView_TagsNeverCarryKindAsANamespacedTag is this fix's
// own regression guard (P1.5, inmaps-spec section 3): kind already has
// its own dedicated frontmatter field on a source view -- putting it into
// tags a second time as "kind/doc" is both namespaced (violating the
// flat-lowercase tag rule) and a kind value in tags at all (which section
// 3 forbids outright). The fixture's own Kind is "kind/doc", so if this
// regresses, this test fails on the fixture default -- no separate broken
// fixture is needed to catch it.
func TestGenerateSourceView_TagsNeverCarryKindAsANamespacedTag(t *testing.T) {
	out := GenerateSourceView(fixtureEntry(), time.Now())
	line := ""
	for _, l := range strings.Split(out, "\n") {
		if strings.HasPrefix(l, "tags: ") {
			line = l
			break
		}
	}
	if line == "" {
		t.Fatalf("no tags: line found:\n%s", out)
	}
	if strings.Contains(line, "/") {
		t.Fatalf("tags line carries a namespaced (slash-containing) value: %q", line)
	}
	if !strings.Contains(out, "kind: \"kind/doc\"") {
		t.Fatalf("kind's own dedicated frontmatter field is missing or changed:\n%s", out)
	}
}

func TestWriteViewsStaging_WritesOneFilePerEntry(t *testing.T) {
	dir := t.TempDir()
	entries := []RegisterEntry{fixtureEntry()}
	n, err := WriteViewsStaging(entries, dir, time.Now())
	if err != nil {
		t.Fatalf("WriteViewsStaging: %v", err)
	}
	if n != 1 {
		t.Fatalf("n = %d, want 1", n)
	}
	path := filepath.Join(dir, "05 - Sources", "SRC-2026-09-06-001.md")
	if _, err := os.Stat(path); err != nil {
		t.Fatalf("expected view file at %s: %v", path, err)
	}
}

func TestWriteViewsStaging_RerunIsConsistentAfterPartialState(t *testing.T) {
	dir := t.TempDir()
	stagingSources := filepath.Join(dir, "05 - Sources")
	os.MkdirAll(stagingSources, 0o755)
	// Simulate a leftover partial write from an interrupted prior run.
	os.WriteFile(filepath.Join(stagingSources, "SRC-2026-09-06-001.md.tmp"), []byte("garbage"), 0o644)

	entries := []RegisterEntry{fixtureEntry()}
	if _, err := WriteViewsStaging(entries, dir, time.Now()); err != nil {
		t.Fatalf("WriteViewsStaging: %v", err)
	}
	data, err := os.ReadFile(filepath.Join(stagingSources, "SRC-2026-09-06-001.md"))
	if err != nil {
		t.Fatalf("reading regenerated view: %v", err)
	}
	if strings.Contains(string(data), "garbage") {
		t.Fatalf("regenerated view carried over stale partial content")
	}
}

// TestWriteViewsStaging_RefusesHandAuthoredPerEntryView is the "zero test
// coverage" gap Lane A's review flagged, non-blocking, on the per-entry
// guard that already existed before this fix: a view file lacking this
// package's own "GENERATED by cmd/sourcecatalogue" marker must be
// refused -- backed up nowhere, overwritten never -- because it looks
// hand-authored rather than a prior run's own output.
func TestWriteViewsStaging_RefusesHandAuthoredPerEntryView(t *testing.T) {
	dir := t.TempDir()
	stagingSources := filepath.Join(dir, "05 - Sources")
	if err := os.MkdirAll(stagingSources, 0o755); err != nil {
		t.Fatal(err)
	}
	handAuthored := "# Someone's own notes about this source\n\nNot generated by anything.\n"
	viewPath := filepath.Join(stagingSources, "SRC-2026-09-06-001.md")
	if err := os.WriteFile(viewPath, []byte(handAuthored), 0o644); err != nil {
		t.Fatal(err)
	}

	entries := []RegisterEntry{fixtureEntry()}
	if _, err := WriteViewsStaging(entries, dir, time.Now()); err == nil {
		t.Fatal("WriteViewsStaging silently overwrote a hand-authored per-entry view -- want a refusal error")
	} else if !strings.Contains(err.Error(), "refusing to overwrite unmanaged source view") {
		t.Fatalf("err = %v, want a message naming the refusal", err)
	}

	got, err := os.ReadFile(viewPath)
	if err != nil {
		t.Fatal(err)
	}
	if string(got) != handAuthored {
		t.Fatal("hand-authored per-entry view was modified despite the refusal")
	}
}

// TestWriteViewsStaging_RefusesHandAuthoredIndex is the fix for the
// defect Lane A's review found already manifested live: the generated
// hub (02 - MOCs/Sources.md, moved there from 05 - Sources/index.md by
// P10, run/iteration-queue.md) had no equivalent "unmanaged content"
// refusal at all -- it backed up (to a hidden temp dir, never
// auto-restored) and unconditionally overwrote whatever was there,
// generated or hand-authored. This proves the hub is now refused, not
// clobbered, exactly like the per-entry guard above.
func TestWriteViewsStaging_RefusesHandAuthoredIndex(t *testing.T) {
	dir := t.TempDir()
	stagingMocs := filepath.Join(dir, "02 - MOCs")
	if err := os.MkdirAll(stagingMocs, 0o755); err != nil {
		t.Fatal(err)
	}
	handAuthored := "# Sources\n\nCurated by hand: see the seed-knowledge-source-artifacts fact.\n"
	hubPath := filepath.Join(stagingMocs, "Sources.md")
	if err := os.WriteFile(hubPath, []byte(handAuthored), 0o644); err != nil {
		t.Fatal(err)
	}

	entries := []RegisterEntry{fixtureEntry()}
	if _, err := WriteViewsStaging(entries, dir, time.Now()); err == nil {
		t.Fatal("WriteViewsStaging silently overwrote a hand-authored hub -- want a refusal error")
	} else if !strings.Contains(err.Error(), "refusing to overwrite unmanaged source hub") {
		t.Fatalf("err = %v, want a message naming the refusal", err)
	}

	got, err := os.ReadFile(hubPath)
	if err != nil {
		t.Fatal(err)
	}
	if string(got) != handAuthored {
		t.Fatal("hand-authored hub was modified despite the refusal -- this is the exact live-run defect")
	}
}

// TestWriteViewsStaging_RegeneratesItsOwnPriorIndex is the other
// direction: a hub this package itself generated before (carries the
// marker) must still regenerate normally on a rerun -- the refusal must
// not become a permanent lock against this package's own output.
func TestWriteViewsStaging_RegeneratesItsOwnPriorIndex(t *testing.T) {
	dir := t.TempDir()
	entries := []RegisterEntry{fixtureEntry()}
	if _, err := WriteViewsStaging(entries, dir, time.Now()); err != nil {
		t.Fatalf("first run: %v", err)
	}
	if _, err := WriteViewsStaging(entries, dir, time.Now()); err != nil {
		t.Fatalf("second run against its own prior output: %v", err)
	}
	data, err := os.ReadFile(filepath.Join(dir, "02 - MOCs", "Sources.md"))
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(data), "GENERATED by cmd/sourcecatalogue") {
		t.Fatal("regenerated hub lost its own generated marker")
	}
}

func min(a, b int) int {
	if a < b {
		return a
	}
	return b
}
