// Command namingdebtbaseline regenerates
// internal/reposcan/testdata/naming_debt_baseline.json from the current
// tree. Maintenance tool, not part of CI -- see
// scripts/tui/refresh-naming-debt-baseline.sh, which is the entry point an
// operator actually runs; this command is its worker, same split as
// internal/reposcan/testdata/known_references.txt's own
// scripts/tui/refresh-known-references.sh.
package main

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/jonhill90/agent-tui/internal/reposcan"
)

func main() {
	root := "."
	if len(os.Args) > 1 {
		root = os.Args[1]
	}

	counts, err := reposcan.NamingDebtCounts(root)
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}

	out := struct {
		Doc    string         `json:"_doc"`
		Counts map[string]int `json:"counts"`
	}{
		Doc: "Pinned per-file forbidden-reference counts for internal/reposcan's " +
			"naming-debt guard (agent-estate#768 item 4, " +
			"TestNamingDebtDoesNotIncreaseOnMain). Generated by " +
			"scripts/tui/refresh-naming-debt-baseline.sh -- do not hand-edit. A file's " +
			"count here is the number of EXISTING hill90-supervisor / " +
			"hill90-codex-supervisor / unqualified agent-supervisor references " +
			"grandfathered pending the deferred sweeps (agent-estate#768 items 1-2); " +
			"the guard fails if a file's live count ever exceeds what is recorded here. " +
			"Regenerate only after a legitimate sweep actually removes references, or " +
			"after adding a NEW file that legitimately needs to cite one historically " +
			"(prefer the inline naming-guard:historical marker for that instead) -- " +
			"never to silence a real new violation.",
		Counts: counts,
	}

	data, err := json.MarshalIndent(out, "", "  ")
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	fmt.Println(string(data))
}
