package shell

import (
	"os"
	"testing"

	"github.com/jonhill90/agent-estate/src/tui/internal/estatus"
	"github.com/jonhill90/agent-estate/src/tui/internal/theme"
)

// TestCaptureHomeFrame renders the Home content pane through the REAL reader
// and writes the frame out, so the evidence in a UI PR can be regenerated by
// a reviewer instead of taken on trust. It skips unless asked:
//
//	CAPTURE_FRAME=/tmp/frame.txt \
//	FRAME_LEDGER=$HOME/.local/state/estate/ledger.jsonl \
//	FRAME_TICKS=docs/tick-log.jsonl \
//	go test ./internal/shell/ -run TestCaptureHomeFrame
//
// It captures the content pane, not the full shell with its sidebar and
// footer -- stated because a frame that is described as more than it is
// becomes evidence for a claim nobody checked.
func TestCaptureHomeFrame(t *testing.T) {
	out := os.Getenv("CAPTURE_FRAME")
	if out == "" {
		t.Skip("set CAPTURE_FRAME=<path> to capture a frame")
	}
	m := Model{
		theme:         theme.Default,
		contentWidth:  92,
		contentHeight: 18,
		estateStatus: func() estatus.Status {
			return estatus.Read(os.Getenv("FRAME_LEDGER"), os.Getenv("FRAME_TICKS"))
		},
	}
	if err := os.WriteFile(out, []byte(m.homeView()), 0o644); err != nil {
		t.Fatal(err)
	}
}
