#!/usr/bin/env bash
# Refresh internal/reposcan/testdata/known_references.txt from GitHub.
#
# Maintenance tool, not part of CI -- internal/reposcan's cross-repo
# reference guard (TestBareIssueReferencesResolveInThisRepository) must run
# offline, so it checks bare '#N' citations against a manifest checked into
# the repository rather than calling the GitHub API itself. Run this
# whenever a new issue or PR is opened and referenced by bare number in a
# tracked doc, or whenever the guard reports a false positive caused by a
# stale manifest:
#
#   scripts/tui/refresh-known-references.sh
#
# Ported from jonhill90/agent-dotfiles' scripts/refresh_known_references.py
# (same manifest format: one number per line, plus leading '#'-comment
# lines, `merge=union` in .gitattributes so two branches that each append a
# different number merge without a conflict).
set -euo pipefail

# This script lives at scripts/tui/ (moved from tui/scripts/ by migration
# Step 2c, #744); the Go module it writes into moved again to src/tui/
# (#865), two levels up plus src/.
repo="jonhill90/agent-tui"
manifest="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../src/tui" && pwd)/internal/reposcan/testdata/known_references.txt"

{
  echo "# generated by scripts/tui/refresh-known-references.sh -- do not hand-edit"
  echo "# repo: ${repo}"
  {
    gh issue list --repo "$repo" --state all --json number --limit 1000 | jq -r '.[].number'
    gh pr list --repo "$repo" --state all --json number --limit 1000 | jq -r '.[].number'
  } | sort -n -u
} > "$manifest"

echo "wrote $(grep -vc '^#' "$manifest") known reference numbers to $manifest"
