package main

import (
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/jonhill90/agent-estate/estate/internal/knowledge"
)

// filteredEnv returns os.Environ() with every variable in drop removed
// and the given overrides appended -- used below to actually UNSET
// AGENT_MEMORY_VAULT for the child process, since appending
// "AGENT_MEMORY_VAULT=" to os.Environ() would still count as set (empty
// string), and knowledge.DefaultConfig treats an empty VaultDir the same
// as an unset one, but this test wants to reproduce the real-world case
// of the variable being genuinely absent from the environment.
func filteredEnv(drop []string, overrides ...string) []string {
	var out []string
	for _, e := range os.Environ() {
		skip := false
		for _, d := range drop {
			if strings.HasPrefix(e, d+"=") {
				skip = true
				break
			}
		}
		if !skip {
			out = append(out, e)
		}
	}
	return append(out, overrides...)
}

// TestKnowledgeRegenerateRefusesCoverageLoss is the end-to-end
// reproduction of agent-estate#1123's live incident: an index on disk
// with vault-facts ok=true, count=109, regenerated by an invocation with
// no $AGENT_MEMORY_VAULT set. Before this fix, `estate knowledge` wrote
// the degraded result over the healthy one and exited 0 whenever every
// OTHER source still read fine. This drives the real compiled binary, not
// knowledge.CoverageRegressions directly, so a regression that
// reintroduces the silent overwrite fails here.
func TestKnowledgeRegenerateRefusesCoverageLoss(t *testing.T) {
	bin := buildEstateBinary(t)
	dir := t.TempDir()
	idx := filepath.Join(dir, "index.json")
	repoRoot := filepath.Join(dir, "repo") // no AGENTS.md -- repo-docs source fails harmlessly
	if err := os.MkdirAll(repoRoot, 0o755); err != nil {
		t.Fatal(err)
	}

	seed := knowledge.Result{
		GeneratedAt: time.Now().UTC(),
		Sources: []knowledge.SourceResult{
			{Name: "vault-facts", OK: true, Count: 109},
		},
		Items: []knowledge.Item{
			{ID: "it-0000000000000109", Source: "vault-fact", Permalink: "/tmp/seed.md",
				Tier1: "seed marker item", Publishable: true, PublishBasis: "vault fact, always public"},
		},
	}
	if err := knowledge.Write(idx, seed); err != nil {
		t.Fatalf("write fixture index: %v", err)
	}
	beforeBytes, err := os.ReadFile(idx)
	if err != nil {
		t.Fatalf("read fixture index before: %v", err)
	}

	env := filteredEnv(
		[]string{"AGENT_MEMORY_VAULT", "ESTATE_CORPUS", "ESTATE_REPO_ROOT"},
		"ESTATE_KNOWLEDGE_INDEX="+idx,
		"ESTATE_LEDGER="+filepath.Join(dir, "ledger.jsonl"),
		"ESTATE_CORPUS="+filepath.Join(dir, "absent-corpus.sqlite3"),
		"ESTATE_REPO_ROOT="+repoRoot,
	)

	cmd := exec.Command(bin, "knowledge")
	cmd.Env = env
	out, runErr := cmd.CombinedOutput()
	code := 0
	if runErr != nil {
		exitErr, ok := runErr.(*exec.ExitError)
		if !ok {
			t.Fatalf("run estate knowledge: %v\n%s", runErr, out)
		}
		code = exitErr.ExitCode()
	}
	if code == 0 {
		t.Fatalf("exit code = 0, want non-zero -- a regeneration that flips vault-facts ok=true -> ok=false must be refused\n%s", out)
	}
	if !strings.Contains(string(out), "vault-facts") || !strings.Contains(string(out), "coverage") {
		t.Errorf("output does not name the coverage regression: %s", out)
	}

	afterBytes, err := os.ReadFile(idx)
	if err != nil {
		t.Fatalf("read fixture index after: %v", err)
	}
	if string(afterBytes) != string(beforeBytes) {
		t.Fatalf("index content changed -- a refused regeneration must not overwrite the index on disk")
	}

	// --allow-coverage-loss overrides the refusal and writes the
	// degraded index -- the escape hatch a legitimate vault-less cron
	// needs once it has actually decided to accept the loss.
	cmd = exec.Command(bin, "knowledge", "--allow-coverage-loss")
	cmd.Env = env
	out, runErr = cmd.CombinedOutput()
	if runErr != nil {
		if _, ok := runErr.(*exec.ExitError); !ok {
			t.Fatalf("run estate knowledge --allow-coverage-loss: %v\n%s", runErr, out)
		}
		// A non-zero exit here is still acceptable (e.g. another source
		// like github-stars also failing in this sandboxed environment
		// triggers the pre-existing "N source(s) could not be read" exit
		// 1) -- what matters is that the WRITE happened.
	}
	res, err := knowledge.Read(idx)
	if err != nil {
		t.Fatalf("read index after --allow-coverage-loss: %v", err)
	}
	for _, s := range res.Sources {
		if s.Name == "vault-facts" && s.OK {
			t.Fatalf("expected vault-facts ok=false after regenerating with no vault configured, got OK=true")
		}
	}
}
