package knowledge

import "testing"

// TestCoverageRegressionsFlagsOKToNotOK is the direct reproduction of the
// live incident agent-estate#1123 reports: an index on disk with
// vault-facts ok=true, count=109, regenerated by a caller with no vault
// configured, producing ok=false, count=0. CoverageRegressions must name
// exactly this.
func TestCoverageRegressionsFlagsOKToNotOK(t *testing.T) {
	prev := Result{Sources: []SourceResult{
		{Name: "vault-facts", OK: true, Count: 109},
		{Name: "github-stars", OK: true, Count: 40},
	}}
	next := Result{Sources: []SourceResult{
		{Name: "vault-facts", OK: false, Reason: "$AGENT_MEMORY_VAULT is not set"},
		{Name: "github-stars", OK: true, Count: 40},
	}}

	got := CoverageRegressions(prev, next)
	if len(got) != 1 {
		t.Fatalf("CoverageRegressions() = %v, want exactly one regression", got)
	}
	want := "vault-facts: ok=true (count=109) -> ok=false ($AGENT_MEMORY_VAULT is not set)"
	if got[0] != want {
		t.Errorf("regression message = %q, want %q", got[0], want)
	}
}

// TestCoverageRegressionsIgnoresCountDrop is the negative case that
// distinguishes this guard's chosen definition from the rejected
// alternative: an ordinary count drop with OK staying true on both sides
// is churn, not a regression, and must not be reported.
func TestCoverageRegressionsIgnoresCountDrop(t *testing.T) {
	prev := Result{Sources: []SourceResult{
		{Name: "github-stars", OK: true, Count: 40},
	}}
	next := Result{Sources: []SourceResult{
		{Name: "github-stars", OK: true, Count: 3},
	}}

	if got := CoverageRegressions(prev, next); len(got) != 0 {
		t.Errorf("CoverageRegressions() = %v, want none -- a count drop with OK=true on both sides is not a regression", got)
	}
}

// TestCoverageRegressionsIgnoresFalseToTrue is the recovery case: a
// source that was failing and is now healthy again is an improvement,
// never a regression.
func TestCoverageRegressionsIgnoresFalseToTrue(t *testing.T) {
	prev := Result{Sources: []SourceResult{
		{Name: "vault-facts", OK: false, Reason: "$AGENT_MEMORY_VAULT is not set"},
	}}
	next := Result{Sources: []SourceResult{
		{Name: "vault-facts", OK: true, Count: 109},
	}}

	if got := CoverageRegressions(prev, next); len(got) != 0 {
		t.Errorf("CoverageRegressions() = %v, want none -- recovery is not a regression", got)
	}
}

// TestCoverageRegressionsIgnoresAlreadyFailing is the steady-state case:
// a source that was already failing and is still failing (a legitimate
// cron with no vault, run twice) must not be flagged on every run.
func TestCoverageRegressionsIgnoresAlreadyFailing(t *testing.T) {
	prev := Result{Sources: []SourceResult{
		{Name: "vault-facts", OK: false, Reason: "$AGENT_MEMORY_VAULT is not set"},
	}}
	next := Result{Sources: []SourceResult{
		{Name: "vault-facts", OK: false, Reason: "$AGENT_MEMORY_VAULT is not set"},
	}}

	if got := CoverageRegressions(prev, next); len(got) != 0 {
		t.Errorf("CoverageRegressions() = %v, want none -- already-failing is not a new regression", got)
	}
}

// TestCoverageRegressionsIgnoresUnknownSourceName is a defensive check:
// a name in one Result but not the other (a hand-edited file, a foreign
// artifact) is not this function's problem to diagnose.
func TestCoverageRegressionsIgnoresUnknownSourceName(t *testing.T) {
	prev := Result{Sources: []SourceResult{
		{Name: "some-future-source", OK: true, Count: 5},
	}}
	next := Result{Sources: []SourceResult{
		{Name: "vault-facts", OK: false, Reason: "$AGENT_MEMORY_VAULT is not set"},
	}}

	if got := CoverageRegressions(prev, next); len(got) != 0 {
		t.Errorf("CoverageRegressions() = %v, want none -- no shared source name to compare", got)
	}
}
