#!/bin/bash
# Install a `tmux` wrapper on PATH ahead of the real binary, so a bare
# destructive verb TYPED INTO A LANE'S OWN SHELL is refused -- not just one
# that reaches a script that calls assert_isolated_tmux (tmux-isolation.sh).
#
# agent-supervisor#166: the tmux server has gone down four times, every time
# because a lane's agent typed `tmux kill-server` directly into its own
# shell. `#247`'s `assert_isolated_tmux` guards SCRIPTS in this repo that
# call it -- it cannot see a command an agent decides to type, because
# nothing routes that keystroke through this repo's code at all. The fourth
# outage happened in a lane whose OWN transcript had just written the
# isolation rule down, moments before running the bare command anyway --
# brief-level reinforcement was tried and failed in the reproduction itself
# (issue #166's own text). The fix has to sit somewhere a typed command
# cannot avoid: the `tmux` binary a lane's shell actually resolves.
#
# SOURCE this file for install_tmux_guard / tmux_guard_bin_dir; it defines
# functions and runs nothing on its own.
#
# What counts as isolated -- deliberately the SAME two techniques
# tmux-isolation.sh / tmux_verb_guard.py already document and test suites
# already use, not a third one invented here:
#   A. TMUX unset AND TMUX_TMPDIR set to an existing directory (the
#      env -u TMUX TMUX_TMPDIR=... shape issue #166 itself names as the
#      correct containment).
#   B. an explicit -L <name> or -S <path> on the command line, naming a
#      socket other than the one this shell is attached to.
#
# `kill-server` has no target -- it always destroys the whole server it
# reaches -- so it is refused unless the invocation is isolated by A or B.
# `kill-session`/`kill-window` DO have a target, and every production caller
# in this repo already passes one explicitly (`transport.py`'s kill_session,
# grep confirms nothing here calls either bare) -- so those two are refused
# only when BOTH isolation is absent AND no `-t` was given, which is exactly
# the shape of a lane typing the bare form and never the shape of a script
# doing its job.
set -u

TMUX_GUARD_MARKER="# agent-supervisor#166 tmux guard wrapper"

tmux_guard_bin_dir() {
  local state_dir="${AGENT_SUPERVISOR_STATE_DIR:-$HOME/.local/state/agent-dotfiles-supervisor}"
  printf '%s\n' "$state_dir/tmux-guard/bin"
}

# Resolve the REAL tmux binary -- the first one on PATH that is not inside
# a tmux-guard bin dir itself (so re-running this against a shell that
# already has the guard on PATH does not wrap the wrapper and recurse).
_tmux_guard_real_tmux() {
  local dir
  local IFS=:
  for dir in $PATH; do
    [ -n "$dir" ] || continue
    case "$dir" in
      */tmux-guard/bin) continue ;;
    esac
    if [ -x "$dir/tmux" ]; then
      printf '%s\n' "$dir/tmux"
      return 0
    fi
  done
  return 1
}

# install_tmux_guard [real_tmux_path]
# Idempotently (re)write the wrapper, embedding an absolute REAL_TMUX path.
# Prints the bin dir on stdout; that dir must be put ahead of the rest of
# PATH by the caller (bootstrap-session.sh / restore.sh, at the moment a
# lane's agent process is launched).
install_tmux_guard() {
  local real_tmux="${1:-}"
  if [ -z "$real_tmux" ]; then
    real_tmux="$(_tmux_guard_real_tmux)" || {
      echo "install_tmux_guard: no real tmux found on PATH" >&2
      return 1
    }
  fi
  case "$real_tmux" in
    /*) ;;
    *) echo "install_tmux_guard: real tmux path must be absolute, got '$real_tmux'" >&2; return 1 ;;
  esac
  if [ ! -x "$real_tmux" ]; then
    echo "install_tmux_guard: not executable: $real_tmux" >&2
    return 1
  fi

  local bin_dir
  bin_dir="$(tmux_guard_bin_dir)"
  mkdir -p "$bin_dir" || return 1
  local wrapper="$bin_dir/tmux"

  # Idempotent: only rewrite when absent or pointing at a different real
  # binary, so re-running this on every dispatch does not touch mtime/needs
  # no separate "already installed" bookkeeping.
  if [ -f "$wrapper" ] && grep -qF "$TMUX_GUARD_MARKER" "$wrapper" 2>/dev/null \
     && grep -qF "REAL_TMUX=\"$real_tmux\"" "$wrapper" 2>/dev/null; then
    printf '%s\n' "$bin_dir"
    return 0
  fi

  cat > "$wrapper" <<WRAPPER
#!/bin/bash
$TMUX_GUARD_MARKER
# Generated by scripts/supervisor/tmux-guard.sh -- do not edit by hand.
REAL_TMUX="$real_tmux"

destructive=""
for a in "\$@"; do
  case "\$a" in
    kill-server|kill-session|kill-window) destructive="\$a"; break ;;
  esac
done

if [ -z "\$destructive" ]; then
  exec "\$REAL_TMUX" "\$@"
fi

isolated=0
if [ -z "\${TMUX:-}" ] && [ -n "\${TMUX_TMPDIR:-}" ] && [ -d "\${TMUX_TMPDIR:-}" ]; then
  isolated=1
fi
for a in "\$@"; do
  case "\$a" in
    -L|-L*|-S|-S*) isolated=1 ;;
  esac
done

if [ "\$isolated" = 1 ]; then
  exec "\$REAL_TMUX" "\$@"
fi

if [ "\$destructive" != "kill-server" ]; then
  has_target=0
  for a in "\$@"; do
    case "\$a" in
      -t|-t*) has_target=1 ;;
    esac
  done
  if [ "\$has_target" = 1 ]; then
    exec "\$REAL_TMUX" "\$@"
  fi
fi

cat >&2 <<MSG
tmux-guard: refusing bare 'tmux \$destructive' -- agent-supervisor#166.
  This has taken the live tmux server down four times: a bare kill-server
  (or an untargeted kill-session/kill-window) run from a lane's own shell
  destroys every session on the box, not just this one.
  Isolated form: env -u TMUX TMUX_TMPDIR=\\\$(mktemp -d) tmux -L <name> \$destructive
  Targeted form (kill-session/kill-window only): tmux \$destructive -t <target>
MSG
exit 1
WRAPPER
  chmod +x "$wrapper"
  printf '%s\n' "$bin_dir"
}
